spring.application.name=salesexpress

# -----------------------------------------------------------------------------
# Conexão com o PostgreSQL (Dados extraídos do docker-compose)
# -----------------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------------------------------------------------------
# Configurações do Hibernate / JPA
# -----------------------------------------------------------------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Atualiza o schema do banco automaticamente com base nas suas entidades (@Entity)
spring.jpa.hibernate.ddl-auto=update

# Exibe as queries SQL formatadas no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
